### ISSUE TITLE
No documentation for adding digikey libraries

### ISSUE THREAD

**Issue by gbip** [ClubRobotInsat/kicad#12]
Hey @dotsumae it seems that you forgot to add a little bit of documentation on the process of adding digikey's kicad library and I can't open your latest project...

**Comment by dotsumae** [comment]
Done ! The process is the same wheter you want to import the club's libs or DigiKey's. Clone DK's [repository](https://github.com/digikey/digikey-kicad-library) outside of our Kicad reposotory and import their symbols with a ctrl-a
